SELECT * FROM EMP;
DESC DEPT;
SELECT EMPNO, ENAME FROM EMP;
--SET PAGESIZE 15
--SET LINESIZE 200
SELECT ENAME NAME, 'good morning~~!' "Good Morning" FROM EMP;
SELECT DNAME, ',it''s deptno: ', deptno "DNAME AND DEPTNO" FROM DEPT;
SELECT DNAME, q'[, it' deptno : ]', deptno "DNAME AND DEPTNO" FROM DEPT;
SELECT ENAME "NAME", JOB AS "JOBB" FROM EMP;
SELECT DISTINCT DEPTNO FROM EMP;
SELECT JOB, ENAME FROM EMP ORDER BY 1,2;
SELECT DISTINCT JOB, ENAME FROM EMP ORDER BY 1,2;
SELECT ENAME || JOB FROM EMP;
SELECT ENAME || '-' || JOB FROM EMP;
SELECT ENAME ||' ''s job is ' || JOB "NAME AND JOB" FROM EMP;
DESC emp;
SELECT NAME ||'''s ID: '||ID||' , WEIGHT is '|| WEIGHT ||'Kg' "ID AND WEIGHT" FROM STUDENT;
SELECT ENAME||'('||JOB||'), '||ENAME||''''||JOB||'''' "NAME AND JOB" FROM EMP;
SELECT ENAME||'''s sal is $'||SAL "Name And Sal" FROM EMP;








